create database NVTK22CNT1Lesson10
go
use NVTK22CNT1Lesson10
go

-- Create table Khoa
CREATE TABLE NVTKhoa (
    NVTMaKH INT PRIMARY KEY,
    NVTTenKH NVARCHAR(50) NOT NULL
);

-- Create table SinhVien
CREATE TABLE NVTSinhVien (
    NVTMaSV INT PRIMARY KEY,
    NVTHoSV NVARCHAR(50) NOT NULL,
    NVTTenSV NVARCHAR(50) NOT NULL,
    NVTPhai CHAR(1) NOT NULL,
    NVTNgaySinh DATE NOT NULL,
    NVTNoiSinh NVARCHAR(50) NOT NULL,
    NVTMaKH INT,
    NVTHocBong DECIMAL(10, 2),
    NVTDiemTrungBinh DECIMAL(3, 2),
    FOREIGN KEY (NVTMaKH) REFERENCES NVTKhoa(NVTMaKH)
);

-- Create table MonHoc
CREATE TABLE NVTMonHoc (
    NVTMaMH INT PRIMARY KEY,
    NVTTeNVT NVARCHAR(50) NOT NULL,
    NVTSoTiet INT NOT NULL
);

CREATE TABLE NVTKetQua (
    NVTMaSV INT,
    NVTMaMH INT,
    NVTDiem DECIMAL(4, 2) NOT NULL,
    PRIMARY KEY (NVTMaSV, NVTMaMH),
    FOREIGN KEY (NVTMaSV) REFERENCES NVTSinhVien(NVTMaSV),
    FOREIGN KEY (NVTMaMH) REFERENCES NVTMonHoc(NVTMaMH)
);