//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVTLesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvtKetQua
    {
        public string NvtMaSV { get; set; }
        public string NvtMaMH { get; set; }
        public Nullable<decimal> NvtDiem { get; set; }
    
        public virtual NvtMonHoc NvtMonHoc { get; set; }
        public virtual NvtSinhVien NvtSinhVien { get; set; }
    }
}
