//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVTLesson10.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NVTK22CNT1Lesson10Entities : DbContext
    {
        public NVTK22CNT1Lesson10Entities()
            : base("name=NVTK22CNT1Lesson10Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NvtKetQua> NvtKetQuas { get; set; }
        public virtual DbSet<NvtKhoa> NvtKhoas { get; set; }
        public virtual DbSet<NvtMonHoc> NvtMonHocs { get; set; }
        public virtual DbSet<NvtSinhVien> NvtSinhViens { get; set; }
    }
}
