//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVTLesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvtMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NvtMonHoc()
        {
            this.NvtKetQuas = new HashSet<NvtKetQua>();
        }
    
        public string NvtMaMH { get; set; }
        public string NvtTenMH { get; set; }
        public Nullable<int> NvtSoTiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NvtKetQua> NvtKetQuas { get; set; }
    }
}
