//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVTLesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NvtSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NvtSinhVien()
        {
            this.NvtKetQuas = new HashSet<NvtKetQua>();
        }
    
        public string NvtMaSV { get; set; }
        public string NvtHoSV { get; set; }
        public string NvtTenSV { get; set; }
        public Nullable<bool> NvtPhai { get; set; }
        public Nullable<System.DateTime> NvtNgaySinh { get; set; }
        public string NvtNoiSinh { get; set; }
        public string NvtMaKH { get; set; }
        public Nullable<decimal> NvtHocBong { get; set; }
        public Nullable<decimal> NvtDiemTrungBinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NvtKetQua> NvtKetQuas { get; set; }
        public virtual NvtKhoa NvtKhoa { get; set; }
    }
}
